title: AI-Enhanced Education
description: Empowering educators with AI tools and resources
baseurl: "/AI-Enhanced-Education" # the subpath of your site
url: "https://teaghan.github.io" # the base hostname & protocol for your site
theme: jekyll-theme-leap-day